name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pull docker image
        run:  docker pull marjunr/recruiter-chatnotificationservice
      - name: delete old docker image
        run:  docker rm -f chatnotification-service || true
      - name: run docker container
        run:  docker run -d -p 8085:8085 --name chatnotification-service --network recruiter-net marjunr/recruiter-chatnotificationservice
